import test, { before, after } from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import WebSocket from 'ws';
import { createServer } from 'node:http';
import { rm, readFile } from 'node:fs/promises';
let server;
const base='http://127.0.0.1:4317';
before(async()=>{server=spawn(process.execPath,['--import','tsx','apps/server/src/index.ts'],{stdio:'ignore',env:{...process.env,INDUS_AUTO_LOCAL_MODEL:'0'}});let ready=false;for(let i=0;i<80;i++){try{const response=await fetch(`${base}/api/health`);if(response.ok){ready=true;break}}catch{}await new Promise(resolve=>setTimeout(resolve,150))}assert.equal(ready,true,'local project API should start')});
after(()=>{server?.kill('SIGTERM')});
test('health and project listing respond',async()=>{const health=await(await fetch(`${base}/api/health`)).json();assert.equal(health.ok,true);const files=await(await fetch(`${base}/api/files`)).json();assert.ok(Array.isArray(files));assert.ok(files.some(file=>file.name==='package.json'))});
test('file API rejects paths outside the selected project',async()=>{const response=await fetch(`${base}/api/file?path=${encodeURIComponent('../package.json')}`);assert.equal(response.status,400)});
test('command API blocks unsupported shortcuts',async()=>{const response=await fetch(`${base}/api/command`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({command:'rm -rf .'})});assert.equal(response.status,403)});
test('terminal WebSocket launches a persistent shell in the project',async()=>{const ws=new WebSocket('ws://127.0.0.1:4317/terminal',{origin:'http://127.0.0.1:5173'});let received='';const input=process.platform==='win32'?'cd apps\r\recho INDUS_SHELL_OK\r':"cd apps\rpwd\rprintf 'INDUS_SHELL_OK\\n'\r";await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error(`shell timed out: ${received}`)),8000);ws.on('open',()=>ws.send(JSON.stringify({type:'input',data:input})));ws.on('message',raw=>{received+=raw.toString();if(received.includes('INDUS_SHELL_OK')){clearTimeout(timer);resolve()}});ws.on('error',reject)});assert.match(received,/INDUS_SHELL_OK/);assert.match(received,/[\\/]apps/);ws.close()});
test('terminal refuses browser origins outside the local app',async()=>{const ws=new WebSocket('ws://127.0.0.1:4317/terminal',{origin:'https://example.com'});await new Promise(resolve=>{ws.on('unexpected-response',(_req,res)=>{assert.equal(res.statusCode,403);resolve()});ws.on('error',()=>resolve())})});

test('AI builder returns a reviewable file proposal',async()=>{
 const body={summary:'Add a small sample file',files:[{path:'tests/.indus-proposal-check.txt',content:'review me'}]};
 const mock=createServer((req,res)=>{req.resume();req.on('end',()=>{res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify(body)}}]}))})});
 await new Promise(resolve=>mock.listen(0,'127.0.0.1',resolve));const port=mock.address().port;
 try{const response=await fetch(`${base}/api/agent/plan`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task:'Add a sample file',baseUrl:`http://127.0.0.1:${port}/v1`,model:'fixture',providerType:'compatible',apiKey:''})});const data=await response.json();assert.equal(response.status,200);assert.equal(data.files[0].path,'tests/.indus-proposal-check.txt');assert.equal(data.summary,body.summary)}finally{await new Promise(resolve=>mock.close(resolve))}
});
test('AI builder rejects unsafe generated paths',async()=>{
 const mock=createServer((req,res)=>{req.resume();req.on('end',()=>{res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:JSON.stringify({files:[{path:'../outside.txt',content:'no'}]})}}]}))})});
 await new Promise(resolve=>mock.listen(0,'127.0.0.1',resolve));const port=mock.address().port;
 try{const response=await fetch(`${base}/api/agent/plan`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({task:'Test path guard',baseUrl:`http://127.0.0.1:${port}/v1`,model:'fixture',providerType:'compatible'})});assert.equal(response.status,502);assert.match((await response.json()).error,/Unsafe project path/)}finally{await new Promise(resolve=>mock.close(resolve))}
});
test('AI apply writes approved files inside the project',async()=>{
 const relative=`tests/.indus-apply-${Date.now()}.txt`,content='approved fixture';
 try{const response=await fetch(`${base}/api/agent/apply`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({files:[{path:relative,content}]})});assert.equal(response.status,200);assert.equal(await readFile(relative,'utf8'),content)}finally{await rm(relative,{force:true})}
});
async function mockProvider(handler){const mock=createServer((req,res)=>{let raw='';req.on('data',chunk=>raw+=chunk);req.on('end',()=>handler(req,res,raw))});await new Promise(resolve=>mock.listen(0,'127.0.0.1',resolve));return{url:`http://127.0.0.1:${mock.address().port}/v1`,close:()=>new Promise(resolve=>mock.close(resolve))}}
test('Anthropic profiles use the Messages API adapter',async()=>{const mock=await mockProvider((req,res)=>{assert.match(req.url,/\/messages$/);assert.equal(req.headers['x-api-key'],'fixture-secret');assert.equal(req.headers['anthropic-version'],'2023-06-01');res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({content:[{type:'text',text:'Anthropic adapter ok'}]}))});try{const response=await fetch(`${base}/api/llm`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseUrl:mock.url,apiKey:'fixture-secret',model:'fixture',providerType:'anthropic',messages:[{role:'user',content:'Hello'}]})});assert.equal((await response.json()).content,'Anthropic adapter ok')}finally{await mock.close()}});
test('Gemini profiles use the GenerateContent API adapter',async()=>{const mock=await mockProvider((req,res)=>{assert.match(req.url,/models\/fixture:generateContent\?key=fixture-key/);res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({candidates:[{content:{parts:[{text:'Gemini adapter ok'}]}}]}))});try{const response=await fetch(`${base}/api/llm`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseUrl:mock.url,apiKey:'fixture-key',model:'fixture',providerType:'gemini',messages:[{role:'user',content:'Hello'}]})});assert.equal((await response.json()).content,'Gemini adapter ok')}finally{await mock.close()}});
test('OpenAI-compatible profiles send model, messages, and bearer key',async()=>{const mock=await mockProvider((req,res,raw)=>{assert.match(req.url,/\/chat\/completions$/);assert.equal(req.headers.authorization,'Bearer fixture-key');const data=JSON.parse(raw);assert.equal(data.model,'fixture');assert.equal(data.messages[0].content,'Hello');res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify({choices:[{message:{content:'Compatible adapter ok'}}]}))});try{const response=await fetch(`${base}/api/llm`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({baseUrl:mock.url,apiKey:'fixture-key',model:'fixture',providerType:'compatible',messages:[{role:'user',content:'Hello'}]})});assert.equal((await response.json()).content,'Compatible adapter ok')}finally{await mock.close()}});
test('debug reproduction endpoint runs only approved test/build commands',async()=>{const safe=await fetch(`${base}/api/debug/reproduce`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command:'npm run build'})});const result=await safe.json();assert.equal(safe.status,200);assert.equal(result.code,0);assert.match(result.stdout,/vite/);for(const command of ['npm test; rm -rf .','npm run deploy']){const blocked=await fetch(`${base}/api/debug/reproduce`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command})});assert.equal(blocked.status,403)}});
test('debug reproduction returns failed command output and exit status',async()=>{const response=await fetch(`${base}/api/debug/reproduce`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command:'npm test -- --indus-unknown-option'})});const result=await response.json();assert.equal(response.status,200);assert.notEqual(result.code,0);assert.match(result.stderr,/bad option/i)});
test('symbol graph reports project declarations, relative imports, and call references',async()=>{const response=await fetch(`${base}/api/graph`);const graph=await response.json();assert.equal(response.status,200);assert.ok(graph.symbols.some(symbol=>symbol.name==='App'&&symbol.kind==='function'));assert.ok(graph.edges.some(edge=>edge.from==='apps/desktop/src/main.tsx'&&edge.to==='apps/desktop/src/style.css'));assert.ok(graph.calls.length>0)});
test('mobile scan separates installed tools from project markers',async()=>{const response=await fetch(`${base}/api/mobile/status`,{method:'POST'});const status=await response.json();assert.equal(response.status,200);assert.ok(Array.isArray(status.platforms));assert.equal(typeof status.tools.swift.available,'boolean');assert.ok(status.builds&&'android'in status.builds&&'ios'in status.builds)});
test('mobile build endpoint accepts only Android or iOS targets',async()=>{const response=await fetch(`${base}/api/mobile/build`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({platform:'linux'})});assert.equal(response.status,400)});
