import express from 'express';
import cors from 'cors';
import fs from 'node:fs/promises';
import path from 'node:path';
import {existsSync} from 'node:fs';
import {createServer} from 'node:http';
import {spawn,execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {WebSocketServer,WebSocket} from 'ws';
const app=express(), exec=promisify(execFile), PORT=Number(process.env.INDUS_PORT)||4317;
const quoteCmd=(value:string)=>`"${String(value).replace(/"/g,'""')}"`;
const run=(bin:string,args:string[]=[],options:any={})=>{if(process.platform==='win32'){const script=bin==='npm'?'npm.cmd':bin==='pnpm'?'pnpm.cmd':bin==='yarn'?'yarn.cmd':bin==='flutter'?'flutter.bat':bin==='gradle'?'gradle.bat':/\.(cmd|bat)$/i.test(bin)?bin:null;if(script){const line=[quoteCmd(script),...args.map(quoteCmd)].join(' ');return exec(process.env.ComSpec||'cmd.exe',['/d','/s','/c',line],{...options,windowsHide:true})}}return exec(bin,args,options)};
const home=process.env.HOME||process.env.USERPROFILE||'',androidSdkDefault=process.platform==='win32'?path.join(process.env.LOCALAPPDATA||path.join(home,'AppData','Local'),'Android','Sdk'):process.platform==='darwin'?path.join(home,'Library','Android','sdk'):path.join(home,'Android','Sdk');
const androidSdkPath=process.env.ANDROID_HOME||process.env.ANDROID_SDK_ROOT||androidSdkDefault;process.env.ANDROID_HOME??=androidSdkPath;process.env.ANDROID_SDK_ROOT??=androidSdkPath;if(process.platform==='win32')process.env.PATH=`${path.join(androidSdkPath,'platform-tools')};${process.env.PATH||''}`;else process.env.PATH=`${path.join(androidSdkPath,'platform-tools')}:${process.env.PATH||''}`;
const allowedOrigins=new Set(['http://127.0.0.1:5173','http://localhost:5173',...(process.env.INDUS_ALLOWED_ORIGIN?[process.env.INDUS_ALLOWED_ORIGIN]:[])]);
app.use(cors({origin(origin,callback){if(!origin||allowedOrigins.has(origin))callback(null,true);else callback(new Error('Origin not allowed'))}}));app.use(express.json({limit:'1mb'}));
let root=path.resolve(process.env.INDUS_PROJECT_ROOT||process.cwd());const safe=(p:string)=>{const q=path.resolve(root,p);if(q!==root&&!q.startsWith(root+path.sep))throw Error('Path escapes project root');return q};
const LOCAL_MODEL='qwen2.5-coder:7b',ollamaCandidates=process.platform==='win32'?[path.join(process.env.LOCALAPPDATA||'','Programs','Ollama','ollama.exe'),path.join(process.env.ProgramFiles||'C:\\Program Files','Ollama','ollama.exe')]:process.platform==='darwin'?['/Applications/Ollama.app/Contents/Resources/ollama','/opt/homebrew/bin/ollama','/usr/local/bin/ollama']:['/usr/local/bin/ollama','/usr/bin/ollama','/opt/homebrew/bin/ollama'];let localState={state:'checking',detail:'Checking local Ollama'},localPull:ReturnType<typeof spawn>|undefined;
app.get('/api/health',(_q,r)=>r.json({ok:true,root}));
app.post('/api/project/open',async(q,r)=>{try{root=path.resolve(String(q.body.path||root));await fs.access(root);r.json({root})}catch(e){r.status(400).json({error:String(e)})}});
app.get('/api/files',async(_q,r)=>{async function walk(dir:string,rel=''):Promise<any[]>{let out:any[]=[];for(const ent of await fs.readdir(dir,{withFileTypes:true})){if(['node_modules','.git','.next','dist','.venv'].includes(ent.name))continue;const p=path.join(dir,ent.name),rp=path.join(rel,ent.name);if(ent.isDirectory())out.push({name:ent.name,path:rp,type:'directory',children:await walk(p,rp)});else out.push({name:ent.name,path:rp,type:'file'})}return out}try{r.json(await walk(root))}catch(e){r.status(500).json({error:String(e)})}});
app.get('/api/file',async(q,r)=>{try{r.type('text').send(await fs.readFile(safe(String(q.query.path||'')),'utf8'))}catch(e){r.status(400).json({error:String(e)})}});
app.put('/api/file',async(q,r)=>{try{const file=safe(String(q.body.path||''));await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,String(q.body.content||''));r.json({ok:true})}catch(e){r.status(400).json({error:String(e)})}});
app.post('/api/command',async(q,r)=>{const command=String(q.body.command||'');const allowed=/^(npm (run|test|install|build|dev)|pnpm (run|test|install|build|dev)|yarn (run|test|install|build|dev)|git (status|diff|log|branch)|python(3)? -m (pytest|unittest)|pytest)(\s[^;&|`$]*)?$/.test(command);if(!allowed)return r.status(403).json({error:'Command not allowed. Use the integrated terminal for other commands.'});try{const [bin,...args]=command.split(/\s+/);const {stdout,stderr}=await run(bin,args,{cwd:root,timeout:120000,maxBuffer:1024*1024});r.json({stdout,stderr,code:0})}catch(e:any){r.json({stdout:e.stdout||'',stderr:e.stderr||e.message,code:typeof e.code==='number'?e.code:1})}});
app.post('/api/debug/reproduce',async(q,r)=>{const command=String(q.body.command||'npm test');const allowed=/^(npm|pnpm|yarn) (test|build|run (test|build|lint|typecheck|check)|-s (test|build|lint|typecheck|check))(\s[^;&|`$]*)?$|^(python(3)? -m (pytest|unittest)|pytest)(\s[^;&|`$]*)?$/.test(command);if(!allowed)return r.status(403).json({error:'Use an approved test, build, lint, typecheck, or check command without shell operators.'});try{const[bin,...args]=command.split(/\s+/);const result=await run(bin,args,{cwd:root,timeout:120000,maxBuffer:1024*1024});r.json({command,stdout:result.stdout,stderr:result.stderr,code:0})}catch(e:any){r.json({command,stdout:e.stdout||'',stderr:e.stderr||e.message,code:typeof e.code==='number'?e.code:1})}});
async function findProjectFiles(dir:string,depth=0,rel=''):Promise<string[]>{if(depth>4)return[];let entries:any[];try{entries=await fs.readdir(dir,{withFileTypes:true})}catch{return[]}const found:string[]=[];for(const ent of entries){if(['.git','node_modules','build','Pods','.gradle','DerivedData'].includes(ent.name))continue;const relative=path.posix.join(rel,ent.name);if(ent.isDirectory()){if(/\.(xcodeproj|xcworkspace)$/.test(ent.name))found.push(relative);else found.push(...await findProjectFiles(path.join(dir,ent.name),depth+1,relative))}else if(/^(settings\.gradle(\.kts)?|build\.gradle(\.kts)?|pubspec\.yaml|Package\.swift)$/.test(ent.name)||ent.name==='gradlew'||ent.name==='gradlew.bat')found.push(relative)}return found}
async function mobileScan(){const result:any={platforms:[],tools:{},builds:{android:{available:false,reason:'No Android project and Gradle/Flutter toolchain detected.'},ios:{available:false,reason:'No iOS project and Xcode/Flutter toolchain detected.'}}};const androidSdk=process.env.ANDROID_HOME||process.env.ANDROID_SDK_ROOT||path.join(process.env.HOME||'','Library','Android','sdk');for(const[bin,args]of Object.entries({adb:['version'],gradle:['--version'],xcodebuild:['-version'],swift:['--version'],flutter:['--version']})){try{const executable=bin==='adb'&&existsSync(path.join(androidSdk,'platform-tools','adb'))?path.join(androidSdk,'platform-tools','adb'):bin;const{stdout,stderr}=await run(executable,args,{cwd:root,timeout:12000,maxBuffer:20000});result.tools[bin]={available:true,path:executable,version:String(stdout||stderr).trim().split('\n').slice(0,2).join(' ')}}catch{result.tools[bin]={available:false}}}
 const files=await findProjectFiles(root);const flutterFile=files.find(x=>x==='pubspec.yaml'||x.endsWith('/pubspec.yaml')),flutterCwd=flutterFile?path.posix.dirname(flutterFile):'.',gradleFile=files.find(x=>/(?:^|\/)(settings|build)\.gradle(\.kts)?$/.test(x)),wrapper=files.find(x=>x==='gradlew'||x==='gradlew.bat'||x.endsWith('/gradlew')||x.endsWith('/gradlew.bat')),xcodeFile=files.find(x=>x.endsWith('.xcworkspace'))||files.find(x=>x.endsWith('.xcodeproj'));let sdkPlatforms:string[]=[];try{sdkPlatforms=await fs.readdir(path.join(androidSdk,'platforms'))}catch{}const hasAndroidSdk=sdkPlatforms.some(name=>/^android-\d/.test(name))&&existsSync(path.join(androidSdk,'build-tools'));
 if(flutterFile&&result.tools.flutter.available){result.platforms.push('flutter');if(hasAndroidSdk){result.builds.android={available:true,kind:'flutter',cwd:flutterCwd,label:'Flutter APK'}}if(result.tools.xcodebuild.available){result.builds.ios={available:true,kind:'flutter',cwd:flutterCwd,label:'Flutter iOS Simulator'}}}
 if(gradleFile&&hasAndroidSdk&&(wrapper||result.tools.gradle.available)){result.platforms.push('android');if(!result.builds.android)result.builds.android={available:true,kind:wrapper?'gradle-wrapper':'gradle',cwd:wrapper?path.posix.dirname(wrapper):path.posix.dirname(gradleFile),label:'Android Debug APK'}}
 if(xcodeFile&&!result.tools.xcodebuild.available){result.builds.ios={available:false,kind:'xcode',file:xcodeFile,schemes:[],label:'iOS Simulator Debug',reason:'Full Xcode is not installed. Install Xcode and open it once to finish setup before building iOS.'}}
 else if(xcodeFile){try{const args=xcodeFile.endsWith('.xcworkspace')?['-list','-json','-workspace',safe(xcodeFile)]:['-list','-json','-project',safe(xcodeFile)];const{stdout}=await run('/usr/bin/xcodebuild',args,{cwd:root,timeout:30000,maxBuffer:200000});const data=JSON.parse(String(stdout)),key=xcodeFile.endsWith('.xcworkspace')?'workspace':'project',schemes=data[key]?.schemes||[];result.builds.ios={available:schemes.length>0,kind:'xcode',file:xcodeFile,schemes,label:'iOS Simulator Debug'};if(schemes.length)result.platforms.push('ios')}catch{result.builds.ios={available:false,kind:'xcode',file:xcodeFile,schemes:[],label:'iOS Simulator Debug',reason:'Could not read an Xcode scheme. Check Xcode installation and project configuration.'}}}
 return result}
app.post('/api/mobile/status',async(_q,r)=>{try{r.json(await mobileScan())}catch(e){r.status(500).json({error:String(e)})}});
app.post('/api/mobile/create',async(q,r)=>{const name=String(q.body.name||'mobile_starter'),relative=String(q.body.path||`examples/${name}`);if(!/^[a-z][a-z0-9_]*$/.test(name))return r.status(400).json({error:'Project name must use lowercase letters, digits, and underscores.'});try{const flutter=process.env.FLUTTER_ROOT?path.join(process.env.FLUTTER_ROOT,'bin','flutter'):existsSync('/opt/homebrew/share/flutter/bin/flutter')?'/opt/homebrew/share/flutter/bin/flutter':'flutter';if(!existsSync(flutter)&&!process.env.PATH?.split(path.delimiter).some(dir=>existsSync(path.join(dir,'flutter'))))return r.status(409).json({error:'Flutter SDK is not installed.'});const rel=path.normalize(relative).replace(/^\.\//,'');if(!rel||rel.startsWith('..')||path.isAbsolute(rel)||/(^|\/)(node_modules|\.git|\.indus)(\/|$)/.test(rel))throw Error('Choose a project folder inside this workspace.');const dest=safe(rel);try{await fs.access(dest);return r.status(409).json({error:`Folder already exists: ${rel}`})}catch{}await fs.mkdir(path.dirname(dest),{recursive:true});const{stdout,stderr}=await run(flutter,['create','--platforms=android,ios','--project-name',name,dest],{cwd:root,timeout:180000,maxBuffer:2*1024*1024});r.json({ok:true,name,path:rel,stdout,stderr})}catch(e:any){r.status(400).json({error:e.stderr||e.message||String(e)})}});
app.post('/api/mobile/build',async(q,r)=>{const platform=String(q.body.platform||'');if(platform!=='android'&&platform!=='ios')return r.status(400).json({error:'Select Android or iOS.'});try{const status=await mobileScan(),target=status.builds[platform];if(!target?.available)return r.status(409).json({error:target?.reason||`No supported ${platform} project and build toolchain were detected.`});let bin:string,args:string[],cwd=path.resolve(root,target.cwd||'.');if(target.kind==='flutter'){bin='flutter';args=platform==='android'?['build','apk']:['build','ios','--simulator']}else if(target.kind==='gradle-wrapper'){bin=path.resolve(root,target.cwd||'.',process.platform==='win32'?'gradlew.bat':'gradlew');args=['assembleDebug']}else if(target.kind==='gradle'){bin='gradle';args=['assembleDebug']}else{const scheme=String(q.body.scheme||'');if(!target.schemes.includes(scheme))return r.status(400).json({error:'Choose a scheme detected in this Xcode project.'});bin='/usr/bin/xcodebuild';args=target.file.endsWith('.xcworkspace')?['-workspace',safe(target.file),'-scheme',scheme,'-configuration','Debug','-destination','generic/platform=iOS Simulator','build']:['-project',safe(target.file),'-scheme',scheme,'-configuration','Debug','-destination','generic/platform=iOS Simulator','build']}
 const startedAt=new Date().toISOString();try{const{stdout,stderr}=await run(bin,args,{cwd,timeout:600000,maxBuffer:8*1024*1024});r.json({ok:true,platform,startedAt,command:target.kind==='xcode'?`xcodebuild ${platform} ${String(q.body.scheme||'')}`:target.kind==='flutter'?`flutter build ${platform==='android'?'apk':'ios'}${platform==='ios'?' --simulator':''}`:platform==='android'?'Gradle assembleDebug':'Mobile build',stdout,stderr,code:0})}catch(e:any){r.json({ok:false,platform,startedAt,command:target.kind==='xcode'?'xcodebuild build':target.kind==='flutter'?`flutter build ${platform==='android'?'apk':'ios'}${platform==='ios'?' --simulator':''}`:'Gradle assembleDebug',stdout:e.stdout||'',stderr:e.stderr||e.message,code:typeof e.code==='number'?e.code:1})}
 }catch(e){r.status(500).json({error:String(e)})}});
app.get('/api/graph',async(_q,r)=>{try{
 const snapshot=await projectSnapshot(),paths=snapshot.manifest.split('\n').filter(Boolean),pathSet=new Set(paths);
 const sourceExt=/\.(tsx?|jsx?|mjs|cjs|py|swift|kt|java)$/i,files:string[]=[],symbols:{file:string;name:string;kind:string;line:number}[]=[],edges:{from:string;to:string;kind:string}[]=[],calls:{from:string;to:string;file:string;line:number}[]=[];
 for(const rel of paths){if(!sourceExt.test(rel))continue;let source='';try{source=await fs.readFile(safe(rel),'utf8')}catch{continue}files.push(rel);
  for(const [index,line]of source.split('\n').entries()){
   const declared=line.match(/^\s*(?:export\s+)?(?:default\s+)?(?:async\s+)?(function|class|interface|type|enum|def|func)\s+([A-Za-z_$][\w$]*)/);
   const variable=line.match(/^\s*(?:export\s+)?(?:const|let|var)\s+([A-Za-z_$][\w$]*)/);
   if(declared)symbols.push({file:rel,name:declared[2],kind:/class/.test(declared[1])?'class':/interface|type|enum/.test(declared[1])?'type':'function',line:index+1});
   else if(variable)symbols.push({file:rel,name:variable[1],kind:/=>|\bfunction\b/.test(line)?'function':'variable',line:index+1});
  }
  const imports=[...source.matchAll(/\bfrom\s*['"]([^'"]+)['"]|require\(\s*['"]([^'"]+)['"]\s*\)|\bimport\s*['"]([^'"]+)['"]/gm)].map(m=>m[1]||m[2]||m[3]).filter(Boolean);
  for(const item of imports){if(!item.startsWith('.'))continue;const base=path.posix.normalize(path.posix.join(path.posix.dirname(rel),item));const candidates=[base,...['.ts','.tsx','.js','.jsx','.mjs','.cjs','.css','.json','.py','.swift','.kt'].map(ext=>base+ext),...['index.ts','index.tsx','index.js','index.jsx'].map(name=>base+'/'+name)];const target=candidates.find(candidate=>pathSet.has(candidate));if(target&&!edges.some(edge=>edge.from===rel&&edge.to===target))edges.push({from:rel,to:target,kind:'imports'})}
 }
 const names=[...new Set(symbols.filter(x=>x.kind==='function').map(x=>x.name))];
 for(const rel of files){let source='';try{source=await fs.readFile(safe(rel),'utf8')}catch{continue}for(const name of names){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const pattern=new RegExp('\\b'+escaped+'\\s*\\(','g');let hit;while((hit=pattern.exec(source))){const line=source.slice(0,hit.index).split('\n').length;if(!symbols.some(symbol=>symbol.file===rel&&symbol.name===name&&symbol.line===line))calls.push({from:'call site',to:name,file:rel,line})}}}
 r.json({files,symbols,edges,calls,limited:paths.length>=100});
 }catch(e){r.status(500).json({error:String(e)})}});
app.get('/api/memory',async(_q,r)=>{try{const file=safe('.indus/memory/PROJECT.md');await fs.mkdir(path.dirname(file),{recursive:true});try{await fs.access(file)}catch{await fs.writeFile(file,'# Project Memory\n\nRecord durable project decisions, conventions, and known issues here.\n')}r.type('text').send(await fs.readFile(file,'utf8'))}catch(e){r.status(500).json({error:String(e)})}});
app.put('/api/memory',async(q,r)=>{try{const file=safe('.indus/memory/PROJECT.md');await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,String(q.body.content||''));r.json({ok:true})}catch(e){r.status(400).json({error:String(e)})}});
app.get('/api/git',async(_q,r)=>{try{const {stdout}=await run('git',['status','--short','--branch'],{cwd:root});r.json({status:stdout})}catch{r.json({status:'Not a Git repository'})}});
async function ollamaStatus(){let installed=ollamaCandidates.some(existsSync),running=false,models:string[]=[];try{const res=await fetch('http://127.0.0.1:11434/api/tags',{signal:AbortSignal.timeout(1200)});if(res.ok){running=true;const body:any=await res.json();models=(body.models||[]).map((m:any)=>m.name)}}catch{}if(!installed){try{await run(process.platform==='win32'?'where.exe':'which',['ollama'],{timeout:1500});installed=true}catch{}}return{installed,running,models,model:LOCAL_MODEL,modelAvailable:models.some(x=>x===LOCAL_MODEL||x.startsWith(LOCAL_MODEL+':')),state:localState.state,detail:localState.detail}}
app.get('/api/local/status',async(_q,r)=>r.json(await ollamaStatus()));
async function startLocalModel(){const initial=await ollamaStatus();if(!initial.installed){localState={state:'missing',detail:'Install Ollama to use the included local model setup.'};return}if(!initial.running){localState={state:'starting',detail:'Starting Ollama'};if(existsSync('/Applications/Ollama.app'))spawn('open',['-a','Ollama'],{stdio:'ignore',detached:true}).unref();else spawn(ollamaCandidates.find(existsSync)||'ollama',['serve'],{stdio:'ignore',detached:true}).unref();for(let i=0;i<50;i++){await new Promise(r=>setTimeout(r,400));if((await ollamaStatus()).running)break}}const current=await ollamaStatus();if(!current.running){localState={state:'offline',detail:'Ollama did not start. Open Ollama and retry.'};return}if(current.modelAvailable){localState={state:'ready',detail:`${LOCAL_MODEL} is ready`};return}if(localPull)return;localState={state:'downloading',detail:`Downloading ${LOCAL_MODEL} (about 4.7 GB)`};localPull=spawn(ollamaCandidates.find(existsSync)||'ollama',['pull',LOCAL_MODEL],{stdio:['ignore','ignore','ignore']});localPull.on('error',e=>{localState={state:'error',detail:e.message};localPull=undefined});localPull.on('close',code=>{localState=code===0?{state:'ready',detail:`${LOCAL_MODEL} is ready`}:{state:'error',detail:`Model download stopped (exit ${code})`};localPull=undefined})}
app.post('/api/local/start',async(_q,r)=>{void startLocalModel();r.json({ok:true,message:'Local model setup started'})});
async function callLLM(input:{baseUrl:string;apiKey:string;model:string;providerType:string;messages:any[]}){
 const{baseUrl,apiKey,model,messages,providerType}=input;let response:Response,data:any;
 if(providerType==='anthropic'){
  const system=messages.filter(m=>m.role==='system').map(m=>m.content).join('\n\n');
  response=await fetch(String(baseUrl).replace(/\/$/,'')+'/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':String(apiKey||''),'anthropic-version':'2023-06-01'},body:JSON.stringify({model,max_tokens:8192,system,messages:messages.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'assistant':'user',content:m.content}))})});data=await response.json();if(!response.ok)throw Error(data.error?.message||`Provider HTTP ${response.status}`);return(data.content||[]).filter((x:any)=>x.type==='text').map((x:any)=>x.text).join('\n');
 }
 if(providerType==='gemini'){
  const system=messages.filter(m=>m.role==='system').map(m=>m.content).join('\n\n'),contents=messages.filter(m=>m.role!=='system').map(m=>({role:m.role==='assistant'?'model':'user',parts:[{text:m.content}]}));
  response=await fetch(`${String(baseUrl).replace(/\/$/,'')}/models/${encodeURIComponent(String(model))}:generateContent?key=${encodeURIComponent(String(apiKey||''))}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({systemInstruction:{parts:[{text:system}]},contents,generationConfig:{temperature:0.15,maxOutputTokens:8192}})});data=await response.json();if(!response.ok)throw Error(data.error?.message||`Provider HTTP ${response.status}`);return data.candidates?.[0]?.content?.parts?.map((x:any)=>x.text||'').join('')||'';
 }
 response=await fetch(String(baseUrl).replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',...(apiKey?{Authorization:`Bearer ${apiKey}`}:{})},body:JSON.stringify({model,messages,temperature:0.15,max_tokens:8192})});data=await response.json();if(!response.ok)throw Error(data.error?.message||`Provider HTTP ${response.status}`);return data.choices?.[0]?.message?.content||'';
}
app.post('/api/llm',async(q,r)=>{try{const content=await callLLM(q.body);r.json({content})}catch(e){r.status(502).json({error:String(e)})}});
async function projectSnapshot(){
 const entries:string[]=[];
 async function walk(dir:string,rel=''){for(const ent of await fs.readdir(dir,{withFileTypes:true})){if(entries.length>=100)return;if(['node_modules','.git','.next','dist','.venv','.swift-cache'].includes(ent.name)||ent.name==='.indus')continue;const rp=path.join(rel,ent.name);if(ent.isDirectory())await walk(path.join(dir,ent.name),rp);else if(ent.isFile())entries.push(rp)}}
 await walk(root);entries.sort((a,b)=>{const rank=(x:string)=>x==='package.json'?0:x==='README.md'?1:/^(src|app|apps)\//.test(x)?2:3;return rank(a)-rank(b)});
 const manifest=entries.join('\n');let budget=8500,count=0;const parts:string[]=[];
 for(const rel of entries){if(count>=12)break;if(/(^|\/)(\.env|\.env\.|credentials|secrets?)([^/]*$)/i.test(rel)||/\.(pem|key|p12)$/i.test(rel))continue;if(!/\.(tsx?|jsx?|css|html?|json|md|py|swift|kt|java|xml|ya?ml|txt)$/i.test(rel))continue;try{const body=await fs.readFile(safe(rel),'utf8');if(body.length>budget)continue;parts.push(`--- ${rel} ---\n${body}`);budget-=body.length;count++;if(budget<500)break}catch{}}
 return{manifest,files:parts.join('\n\n')}
}
function parseProposal(raw:string){const json=raw.match(/\{[\s\S]*\}/)?.[0];if(!json)throw Error('No JSON object in model response');return JSON.parse(json)}
app.post('/api/agent/plan',async(q,r)=>{try{
 const{task,baseUrl,apiKey,model,providerType}=q.body;if(!String(task||'').trim())return r.status(400).json({error:'Describe the app or code change first.'});const snapshot=await projectSnapshot();
 const messages=[{role:'system',content:'You are a code editor that creates project files. Return exactly one valid JSON object and no markdown. Required format: {"summary":"short explanation","files":[{"path":"relative/path","content":"complete file content"}]}. Make the requested app or change runnable, use the supplied project files as context, and keep changes focused. Never include credentials.'},{role:'user',content:`Request: ${task}\n\nProject files (first 100):\n${snapshot.manifest}\n\nSelected project source (compact context):\n${snapshot.files}`}];
 let raw=await callLLM({baseUrl,apiKey,model,providerType,messages}),proposal:any;
 try{proposal=parseProposal(raw)}catch{const repaired=await callLLM({baseUrl,apiKey,model,providerType,messages:[{role:'system',content:'Convert the supplied response into exactly one valid JSON object with shape {"summary":"short explanation","files":[{"path":"relative/path","content":"complete file content"}]}. Preserve its proposed file contents. Return JSON only.'},{role:'user',content:raw.slice(0,12000)}]});proposal=parseProposal(repaired)}
 if(!Array.isArray(proposal.files)||!proposal.files.length)throw Error('The model returned no files. Try a more specific or smaller build request.');if(proposal.files.length>40)throw Error('The proposal is too large (over 40 files).');let bytes=0;
 const files=proposal.files.map((f:any)=>{const rel=path.normalize(String(f.path||'')).replace(/^\.\//,'');if(!rel||rel.startsWith('..')||path.isAbsolute(rel)||/(^|\/)(\.git|node_modules|\.indus)(\/|$)/.test(rel)||/(^|\/)\.env($|\.)/i.test(rel))throw Error(`Unsafe project path in proposal: ${rel}`);const content=String(f.content||'');bytes+=Buffer.byteLength(content);if(bytes>512000)throw Error('The proposal exceeds the 512 KB review limit.');return{path:rel,content}});
 r.json({summary:String(proposal.summary||'Proposed project changes'),files})
 }catch(e){r.status(502).json({error:String(e)})}});
app.post('/api/agent/apply',async(q,r)=>{try{const files=q.body.files;if(!Array.isArray(files)||!files.length||files.length>40)throw Error('Invalid file proposal.');let bytes=0;for(const f of files){const rel=path.normalize(String(f.path||'')).replace(/^\.\//,'');if(!rel||rel.startsWith('..')||path.isAbsolute(rel)||/(^|\/)(\.git|node_modules|\.indus)(\/|$)/.test(rel)||/(^|\/)\.env($|\.)/i.test(rel))throw Error(`Unsafe project path: ${rel}`);const content=String(f.content||'');bytes+=Buffer.byteLength(content);if(bytes>512000)throw Error('The patch exceeds 512 KB.');const target=safe(rel);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,content)}r.json({ok:true,changed:files.map((f:any)=>f.path)})}catch(e){r.status(400).json({error:String(e)})}});
const server=createServer(app),wss=new WebSocketServer({noServer:true});server.on('upgrade',(req,socket,head)=>{const url=new URL(req.url||'','http://127.0.0.1');if(url.pathname!=='/terminal'||!allowedOrigins.has(String(req.headers.origin||''))){socket.write('HTTP/1.1 403 Forbidden\r\n\r\n');socket.destroy();return}wss.handleUpgrade(req,socket,head,ws=>wss.emit('connection',ws,req))});
wss.on('connection',ws=>{const shell=process.env.SHELL&&existsSync(process.env.SHELL)?process.env.SHELL:process.platform==='win32'?(process.env.ComSpec||'cmd.exe'):'/bin/zsh';const shellEnv:Record<string,string|undefined>={...process.env,TERM:'xterm-256color',HISTFILE:'/dev/null',INDUS_PROJECT_ROOT:root};delete shellEnv.npm_config_prefix;const child=spawn(shell,process.platform==='win32'?[]:['-i'],{cwd:root,env:shellEnv,stdio:['pipe','pipe','pipe']});const send=(type:string,data:string)=>{if(ws.readyState===WebSocket.OPEN)ws.send(JSON.stringify({type,data}))};child.stdout.on('data',d=>send('output',d.toString()));child.stderr.on('data',d=>send('output',d.toString()));child.on('error',e=>send('error',e.message));child.on('exit',code=>{send('exit',String(code??0));ws.close()});ws.on('message',raw=>{try{const msg=JSON.parse(raw.toString());if(msg.type==='input'&&typeof msg.data==='string')child.stdin.write(process.platform==='win32'?msg.data.replace(/\r/g,'\r\n'):msg.data.replace(/\r/g,'\n'));else if(msg.type==='interrupt')child.kill('SIGINT')}catch{}});ws.on('close',()=>{if(!child.killed)child.kill('SIGTERM')})});
if(process.env.INDUS_AUTO_LOCAL_MODEL==='0')localState={state:'offline',detail:'Local model is stopped. Start setup from Settings when you are ready.'};
if(process.env.INDUS_STATIC_DIR){app.use(express.static(process.env.INDUS_STATIC_DIR));app.get('*',(_q,r)=>r.sendFile(path.join(process.env.INDUS_STATIC_DIR!,'index.html')))}
server.listen(PORT,'127.0.0.1',()=>{console.log(`Indus backend listening at http://127.0.0.1:${PORT}`);if(process.env.INDUS_AUTO_LOCAL_MODEL!=='0')setTimeout(()=>void startLocalModel(),1500)});
